In [113]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [114]:
df = pd.read_csv('train.csv')

In [115]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [116]:
df.info

<bound method DataFrame.info of           id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2      

In [117]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      20800 non-null  int64 
 1   title   20242 non-null  object
 2   author  18843 non-null  object
 3   text    20761 non-null  object
 4   label   20800 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 812.6+ KB


In [119]:
df['label'].nunique()

2

In [120]:
df = df.dropna()

In [121]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [122]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [123]:
print(X.shape)
print(y.shape)

(18285, 4)
(18285,)


In [124]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: label, dtype: int64

In [125]:
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import one_hot


In [126]:
#vocabulary size
voc_size=5000

<h3> One Hot representation </h3>

In [127]:
message = X.copy()

In [128]:
message.reset_index(inplace=True)
#As we dropped some of the Nan values.

In [129]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [130]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\E0551793\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [131]:
ps=PorterStemmer()
corpus=[]
for i in range(len(message)):
    text = re.sub('[^a-zA-Z]', ' ', message['title'][i])
    text = text.lower()
    text = text.split()

    text = [ps.stem(word) for word in text if not word in stopwords.words('english')]
    text = ' '.join(text)
    corpus.append(text)

In [132]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [133]:
one_hot_rep = [one_hot(word, voc_size) for word in corpus]
one_hot_rep

[[4781, 1773, 1587, 969, 1, 764, 2331, 2929, 4261, 3189],
 [236, 4531, 3822, 2057, 3975, 2189, 2043],
 [3227, 396, 599, 1447],
 [4875, 4464, 1836, 110, 1435, 4312],
 [4735, 3975, 821, 1395, 1512, 642, 3975, 4209, 4739, 4051],
 [1373,
  3296,
  876,
  2913,
  3435,
  3476,
  3620,
  2102,
  2140,
  2528,
  3098,
  482,
  4079,
  2823,
  2043],
 [4825, 2983, 2018, 3259, 4577, 4605, 298, 4873, 3994, 1179, 1429],
 [232, 757, 1428, 733, 650, 2441, 3476, 4854, 3994, 1179, 1429],
 [951, 1650, 306, 4570, 321, 4936, 1072, 4507, 3476, 2426],
 [567, 2771, 2616, 669, 1541, 1615, 3140, 2187],
 [2063, 1009, 4346, 510, 4032, 1041, 345, 4310, 864, 1232, 1882],
 [110, 978, 1, 4936, 3476, 650],
 [2746, 2930, 3029, 4531, 1101, 1711, 2916, 2719, 3472],
 [3752, 3688, 2623, 4227, 239, 4684, 358, 3994, 1179, 1429],
 [2377, 898, 3187, 521, 3305, 3994, 1179, 1429],
 [4362, 889, 342, 793, 2434, 1761, 2411, 3899, 149, 2741],
 [1679, 3330, 4531],
 [1996, 2056, 3736, 3545, 3476, 2300, 3293, 2043],
 [1020, 1061, 38

Padding

In [134]:
sent_len = 20
pad_docs = pad_sequences(one_hot_rep, padding='pre', maxlen=sent_len)
print(pad_docs)

[[   0    0    0 ... 2929 4261 3189]
 [   0    0    0 ... 3975 2189 2043]
 [   0    0    0 ...  396  599 1447]
 ...
 [   0    0    0 ... 3994 1179 1429]
 [   0    0    0 ... 2917 2401 3216]
 [   0    0    0 ... 3596 4584 4534]]


In [135]:
len(pad_docs)

18285

In [136]:
feature_dim = 40
model = Sequential()
model.add(Embedding(voc_size, feature_dim, input_length = sent_len))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

c:\Users\E0551793\OneDrive - Eaton\BLC-Saloni\BITSPilani\FakeNewsClassifier-LSTM\venv\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [147]:
tf.keras.utils.plot_model(model)

You must install pydot (`pip install pydot`) for `plot_model` to work.


In [137]:
import numpy as np
X_final = np.array(pad_docs)
y_final = np.array(y)

In [138]:
len(pad_docs), y.shape

(18285, (18285,))

In [139]:
X_final.shape

(18285, 20)

In [140]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [141]:
y_test

array([1, 0, 0, ..., 0, 1, 1], dtype=int64)

In [142]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=64)

Epoch 1/10


192/192 ━━━━━━━━━━━━━━━━━━━━ 8s 22ms/step - accuracy: 0.7708 - loss: 0.4397 - val_accuracy: 0.9128 - val_loss: 0.1979
Epoch 2/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step - accuracy: 0.9404 - loss: 0.1528 - val_accuracy: 0.9216 - val_loss: 0.2070
Epoch 3/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step - accuracy: 0.9593 - loss: 0.1080 - val_accuracy: 0.9180 - val_loss: 0.2026
Epoch 4/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step - accuracy: 0.9725 - loss: 0.0808 - val_accuracy: 0.9072 - val_loss: 0.2624
Epoch 5/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step - accuracy: 0.9837 - loss: 0.0510 - val_accuracy: 0.9135 - val_loss: 0.2382
Epoch 6/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - accuracy: 0.9854 - loss: 0.0470 - val_accuracy: 0.9145 - val_loss: 0.2761
Epoch 7/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 5s 24ms/step - accuracy: 0.9911 - loss: 0.0326 - val_accuracy: 0.9114 - val_loss: 0.3529
Epoch 8/10
192/192 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step - accuracy: 0.9919 - loss: 0.0258 - val_accuracy: 0.912

Performance Metrics

In [143]:
y_pred = (model.predict(X_test) > 0.5).astype("int32")
# y_pred = np.argmax(y_pred_value,axis=1)

from sklearn.metrics import confusion_matrix

189/189 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step


In [144]:
y_pred

array([[1],
       [0],
       [0],
       ...,
       [0],
       [1],
       [1]])

In [145]:
confusion_matrix(y_test, y_pred)

array([[3080,  339],
       [ 177, 2439]], dtype=int64)

In [146]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9144987572493787

Make Predictions

In [148]:
test_df = pd.read_csv("test.csv")

In [149]:
test_df.head()

id                                              title  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1  20801  Russian warships ready to strike terrorists ne...   
2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4  20804                    Keiser Report: Meme Wars (E995)   

                    author                                               text  
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...  
1                      NaN  Russian warships ready to strike terrorists ne...  
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...  
3            Daniel Victor  If at first you don’t succeed, try a different...  
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...

In [152]:
test_df.isnull().sum()

id        0
title     0
author    0
text      0
dtype: int64

In [151]:
test_df = test_df.dropna()

In [153]:
test_message = test_df.copy()
test_message.reset_index(inplace=True)

In [154]:
ps=PorterStemmer()
corpus=[]
for i in range(len(test_message)):
    text = re.sub('[^a-zA-Z]', ' ', test_message['title'][i])
    text = text.lower()
    text = text.split()

    text = [ps.stem(word) for word in text if not word in stopwords.words('english')]
    text = ' '.join(text)
    corpus.append(text)

In [155]:
corpus

['specter trump loosen tongu purs string silicon valley new york time',
 'nodapl nativ american leader vow stay winter file lawsuit polic',
 'tim tebow attempt anoth comeback time basebal new york time',
 'keiser report meme war e',
 'pelosi call fbi investig find russian donald trump breitbart',
 'weekli featur profil randi shannon',
 'u gener admir endors trump command chief',
 'work class hero john brennon',
 'rise mandatori vaccin mean end medic freedom',
 'communist terror small busi',
 'comput programm come forward admit paid rig vote booth trump right usa newsflash',
 'thiev take chunk chang pound berlin museum new york time',
 'new england patriot owner still sore n f l payback sight new york time',
 'colleg republican yaf sue berkeley ann coulter event breitbart',
 'trump melt accus us postal servic steal elect clinton',
 'visit madagascar leav red swimsuit lemur recip home new york time',
 'rees peanut butter cup cheap full toxic chemic',
 'presid obama presid elect donald tr

In [156]:
one_hot_rep = [one_hot(word, voc_size) for word in corpus]
one_hot_rep

[[153, 3476, 104, 4981, 3974, 4121, 332, 1217, 3994, 1179, 1429],
 [1117, 4661, 4484, 748, 2827, 973, 236, 501, 4999, 2310],
 [297, 293, 959, 4088, 4764, 1429, 3016, 3994, 1179, 1429],
 [2593, 3637, 3288, 2557, 426],
 [4868, 3285, 1679, 4401, 239, 2063, 3545, 3476, 2043],
 [781, 2883, 3464, 2538, 2600],
 [2404, 2808, 4515, 681, 3476, 330, 3187],
 [2959, 1977, 4652, 1808, 4680],
 [317, 1466, 4761, 954, 3305, 369, 4829],
 [3525, 2677, 4707, 951],
 [3508, 2651, 2974, 1460, 1575, 2930, 127, 1126, 1188, 3476, 1853, 2561, 1316],
 [2253, 2555, 82, 2563, 2657, 2605, 2628, 3994, 1179, 1429],
 [3994,
  1538,
  1448,
  436,
  2276,
  3788,
  1049,
  4584,
  4219,
  1107,
  1501,
  3994,
  1179,
  1429],
 [663, 1832, 1043, 4172, 3206, 4870, 2397, 3956, 2043],
 [3476, 4798, 4575, 110, 3607, 42, 1288, 4506, 3822],
 [3709, 1874, 3512, 3492, 4223, 1549, 4641, 4684, 3994, 1179, 1429],
 [3818, 4056, 3541, 118, 347, 3389, 1887, 527],
 [4930, 951, 4930, 4506, 3545, 3476, 3865, 1112, 4781],
 [669, 2680, 28

In [157]:
pad_docs = pad_sequences(one_hot_rep, padding='pre', maxlen=sent_len)
print(pad_docs)

[[   0    0    0 ... 3994 1179 1429]
 [   0    0    0 ...  501 4999 2310]
 [   0    0    0 ... 3994 1179 1429]
 ...
 [   0    0    0 ... 3994 1179 1429]
 [   0    0    0 ... 3994 1179 1429]
 [   0    0    0 ... 3994 1179 1429]]


In [158]:
X_test = np.array(pad_docs)

In [160]:
y_pred = (model.predict(X_test) > 0.5).astype("int32")

143/143 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step


In [163]:
predictions = [int(np.round(pred[0])) for pred in y_pred]
predictions

[0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,


In [167]:
submission = pd.DataFrame({
    "id" : test_df['id'],
    "label" : predictions
})
submission

id  label
0     20800      0
2     20802      0
3     20803      0
4     20804      1
6     20806      0
...     ...    ...
5194  25994      0
5195  25995      0
5196  25996      0
5197  25997      0
5199  25999      0

[4575 rows x 2 columns]

In [168]:
submission.to_csv('submission.csv', index=False)